In [1]:
1+1


2

In [4]:
list_a = list(range(1,100))
print(list_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [5]:
squared= []
for a in list_a:
    sq = a**2
    squared.append(sq)
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [6]:
print([a**2 for a in list_a])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [7]:
import numpy as np



In [8]:
arr1 = np.array(list_a)

In [11]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
arr1**2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [13]:
np.square(arr1)

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [19]:
a221= np.array([range(1,5)])

In [15]:
print(arr2)

[[1 2 3 4]]


In [20]:
arr2= np.arange(10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr3 = np.random.randn()

In [22]:
print(arr3)

[[ 1.23989745 -0.38657133  0.07774046 -0.54577089  1.79193772  1.99420205
  -1.76620029 -1.59960245  1.10593212  1.26136269 -0.3094878  -1.38511558
  -1.22031756  0.22257317  0.60925243  0.0542304  -0.88954778  1.37675148
   0.7825409   0.47246936  0.86378504 -0.33179785  0.3573289   0.57255233
   0.65138114 -0.5788289  -0.41827392  0.11307759  0.88021648 -1.20649183
   1.03169094 -0.27746393  1.23552969 -0.55150702 -0.68692049  0.68959373
   1.23863552  0.60005217 -0.87728682 -1.33294278 -1.1098871   0.43529503
  -1.67522139  0.08108255 -1.05853684  1.9888431  -1.19918632 -0.13399002
   0.55393715 -0.16770984  0.14504671  1.62455877 -0.51106264  0.86197431
   0.15300968  0.58777572 -1.31576878  0.61419735  0.33115071  1.09976968
  -1.14912388  1.87281381 -0.21146298 -0.59478964 -0.30027105 -2.56554291
   0.9933683  -0.85964835 -2.01829072 -0.23409308  0.16630552 -1.12451403
  -1.5554365   1.91061544  0.67547281  0.40445375 -0.94354053  1.5596973
   0.36522682 -0.42321566  0.55711918 -

In [32]:
arr4 = np.random.rand(1,10)

In [26]:
print(arr4)

[[[7.18030877e-01 3.53482283e-01 2.21302318e-01 7.46142901e-01
   3.19385627e-02 3.01969037e-01 1.47689536e-01 3.59450552e-01
   9.75188655e-01 5.04056245e-01 2.25632423e-03 5.35294118e-01
   9.08240027e-01 1.15061014e-01 9.67590831e-01 8.08071694e-01
   7.59452382e-01 6.16390620e-01 3.90041932e-01 4.49720410e-01
   3.97144354e-01 5.93242057e-01 1.11677728e-01 8.92941732e-01
   8.74308790e-01 2.96422423e-02 9.69857668e-01 5.93454508e-01
   5.47434419e-01 5.79848574e-01 2.50092486e-02 9.83540986e-01
   8.65855999e-01 2.88542252e-01 5.72797283e-01 4.87388804e-01
   6.83465062e-01 1.67504289e-01 8.49307594e-01 9.75950494e-01
   4.43632578e-01 2.80852696e-01 1.18649586e-02 3.53981136e-01
   2.35406409e-01 7.17196661e-01 5.46474304e-01 6.09963907e-01
   7.84109602e-01 3.85674916e-01 5.99594985e-01 6.41488621e-01
   3.03002493e-01 5.17179174e-01 1.87276728e-01 3.49242223e-01
   2.15107301e-02 1.69887867e-01 7.07340986e-01 2.24612144e-01
   7.61752526e-01 3.97937716e-01 2.64013889e-01 2.28058

In [29]:
arr4.dtype

dtype('float64')

In [30]:
arr3.dtype

dtype('float64')

In [31]:
arr4.size

1000

In [33]:
arr4.ndim

2

In [34]:
arr4.shape

(1, 10)

In [ ]:
arr1.shape

(99,)

In [37]:
arr2d = np.array([[1,2,3],[4,5,6],[3,2,1],[6,5,4]])

In [38]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]


In [39]:
arr2d.size

12

In [40]:
arr2d.shape

(4, 3)

In [41]:
arr2d.ndim

2

In [ ]:
arr2da = np.random.randa(5,4)

In [44]:
arr2da

array([[0.15182608, 0.85665816, 0.92947009, 0.13191139],
       [0.0737915 , 0.23499047, 0.47965566, 0.35819502],
       [0.01654444, 0.06323479, 0.33204933, 0.68495594],
       [0.90153722, 0.19544886, 0.90856675, 0.02887157],
       [0.69582977, 0.11818037, 0.08815086, 0.5994462 ]])

In [45]:
arr3d = np.random.rand(3,4,5) #create an array of 4 rows 5 column and 3 copies with random number

In [46]:
print(arr3d)

[[[0.92611971 0.43262325 0.52625524 0.75414839 0.60642288]
  [0.7530281  0.87567105 0.6618671  0.98457511 0.8124544 ]
  [0.09489591 0.60228814 0.15875635 0.23681953 0.17416106]
  [0.5144771  0.99470683 0.48857005 0.58198757 0.98985761]]

 [[0.15048622 0.38738321 0.59765648 0.27636207 0.39329947]
  [0.7349586  0.51521421 0.56531874 0.6822319  0.7111277 ]
  [0.65181727 0.58221231 0.57793249 0.67982576 0.19320524]
  [0.67594117 0.73284072 0.71827109 0.45245609 0.87199304]]

 [[0.47643975 0.80613588 0.08857777 0.30254809 0.0167822 ]
  [0.78062787 0.26062265 0.1226324  0.89791076 0.79028742]
  [0.81442203 0.01187722 0.19239168 0.53072989 0.18338128]
  [0.53978793 0.0130816  0.401404   0.09569516 0.27450267]]]


In [47]:
arr3s= np.arange(64).reshape(4,4,4)

In [48]:
print(arr3s)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.ones((4,4))*34

array([[34., 34., 34., 34.],
       [34., 34., 34., 34.],
       [34., 34., 34., 34.],
       [34., 34., 34., 34.]])

In [59]:
np.full((6,6),abd)

array([[23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23]])

In [58]:
abd=23


In [60]:
arr2d1= np.arange(20).reshape(4,5)

In [61]:
arr2d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
arr2d1+arr2d

ValueError: operands could not be broadcast together with shapes (4,5) (4,3) 

In [64]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [ ]:
np.ran

In [69]:
arr1d[4]=1

In [73]:
arr3c= np.arange(2,21,2)

In [74]:
arr3c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arridmt = np.eye(5,5)

In [76]:
arridmt

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Reshape an array
➤ Create an array from 1 to 12 and reshape it into a 3x4 matrix.

Random numbers
➤ Create an array of 5 random integers between 10 and 50.

In [80]:
arq4 = np.arange(1,13).reshape(3,4)

In [81]:
arq4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
arq5 = np.random.randint(10,50,5)
print(arq5)

[35 42 18 10 35]


🔢 Array Operations
Element-wise operations
➤ Given two arrays a = [1, 2, 3] and b = [4, 5, 6], perform:

Addition

Multiplication

Dot product

Conditional filtering
➤ From an array [5, 12, 17, 9, 3, 21, 8], extract all elements greater than 10.

Replace values
➤ Replace all even numbers in an array with -1.

Sum across axes
➤ Create a 3x3 matrix and find the sum of:

Each row

Each column

In [114]:
arq6a= np.array([1, 2, 3])
arq6b= np.array([4, 5, 6])

#arq6a+arq6b


#arq6a*arq6b
a=np.dot(arq6a,arq6b)


In [115]:
a

np.int64(32)

In [ ]:

#Conditional filtering
#➤ From an array [5, 12, 17, 9, 3, 21, 8], extract all elements greater than 10.

arq7=np.array([5, 12, 17, 9, 3, 21, 8])
print(arq7[arq7 > 10])



[12 17 21]


In [137]:
#Replace values
#➤ Replace all even numbers in an array with -1.
a = arq7[arq7 % 2==0] =-1
print(arq7)



[ 5 -1 17  9  3 21 -1]


In [ ]:
arq9 =  np.arange(9).reshape(3,3)
sum_r= np.sum(arq9, axis=1)

sum_c =  np.sum(arq9,axis=0)

In [153]:
arq9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Intermediate Level
Matrix multiplication
➤ Create two 3x3 matrices and multiply them using both * and @. What’s the difference?


In [158]:
a10= np.arange(9).reshape(3,3)
a10b= np.arange(9).reshape(3,3)
a10*a10b

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [159]:
a10@a10b

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [162]:
print(a10b)
print(a10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]



Find max and min with indices
➤ For a given random 5x5 matrix, find the max and min values and their positions (indices).

Normalize an array
➤ Normalize an array so that all values lie between 0 and 1.
a12 = np.random.rand(4)

Sorting

In [ ]:
a11 =  np.random.randint(25,250,size=(5,5))
a11
np.max(a11)
min_a=np.min(a11)
np.argmax(a11)
np.argmin(a11)


np.int64(1)

In [190]:
a12 = np.random.rand(4)

In [191]:
a12

array([0.75848956, 0.58870291, 0.25073829, 0.73840696])

In [192]:
Sorting
➤ Sort the following 2D array by the second column:

python
Copy
Edit


SyntaxError: invalid character '➤' (U+27A4) (965681695.py, line 2)

In [193]:
arr13 = np.array([[3, 7], [1, 9], [5, 2]])

In [194]:
arr13

array([[3, 7],
       [1, 9],
       [5, 2]])

In [ ]:
np.sort(arr13,axis=0)

array([[1, 2],
       [3, 7],
       [5, 9]])

In [141]:
print(arq9)

[]


In [101]:
arq6a.dtype

dtype('int64')